# Generated by Django 2.2.4 on 2019-08-13 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('A3', '0002_auto_20190813_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_corredor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('encargado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='A3.Institucion')),
                ('puntos_fijos', models.ManyToManyField(blank=True, to='A3.PuntosFijos')),
            ],
        ),
    ]
