# Generated by Django 2.2.4 on 2019-08-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0003_corredor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corredor',
            old_name='puntos_fijos',
            new_name='puntos',
        ),
    ]
