# Generated by Django 2.2.4 on 2019-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0004_auto_20190813_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosfijos',
            name='resgistro_fotografico',
            field=models.ImageField(blank=True, upload_to='registros'),
        ),
    ]
