# Generated by Django 2.2.4 on 2019-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0005_puntosfijos_resgistro_fotografico'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='hora_de_ingreso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='hora_de_salida',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
